services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.0
    container_name: miniwiki-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - miniwiki-net
    # https://docs.docker.com/engine/logging/configure/
    # logging:
    #   driver: "none"
    # https://docs.docker.com/reference/compose-file/services/#healthcheck
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
  mongo:
    image: mongo:7
    container_name: miniwiki-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - miniwiki-net
    # logging:
    #   driver: "none"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: miniwiki-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - miniwiki-net
    # logging:
    #   driver: "none"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      cache_from:
        - miniwiki-backend:latest
    image: miniwiki-backend:latest
    container_name: miniwiki-backend
    restart: on-failure
    depends_on:
      mongo:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - ES_URL=http://elasticsearch:9200
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app # in case we want dev live-reload
      - /app/node_modules
    networks:
      - miniwiki-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      cache_from:
        - miniwiki-frontend:latest
    image: miniwiki-frontend:latest
    container_name: miniwiki-frontend
    restart: on-failure
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app # For the Vite dev reload
      - /app/node_modules
    environment:
      - VITE_API_BASE=http://backend:3000
    networks:
      - miniwiki-net

  # RUN ONCE TO SEED
  seed:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: miniwiki-seed
    command: ["npm", "run", "seed"]
    depends_on:
      mongo:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - ES_URL=http://elasticsearch:9200
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - miniwiki-net

volumes:
  esdata:
  mongodata:

networks:
  miniwiki-net:
