services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.0
    container_name: miniwiki-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - miniwiki-net
    # https://docs.docker.com/engine/logging/configure/
    logging:
      driver: "none"
  mongo:
    image: mongo:7
    container_name: miniwiki-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - miniwiki-net
    logging:
      driver: "none"

  redis:
    image: redis:7
    container_name: miniwiki-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - miniwiki-net
    logging:
      driver: "none"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: miniwiki-backend
    restart: on-failure
    depends_on:
      - mongo
      - elasticsearch
      - redis
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - ES_URL=http://elasticsearch:9200
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app # in case we want dev live-reload
      - /app/node_modules
    networks:
      - miniwiki-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: miniwiki-frontend
    restart: on-failure
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app # For the Vite dev reload
      - /app/node_modules
    environment:
      - VITE_API_BASE=http://backend:3000
    networks:
      - miniwiki-net

  # RUN ONCE TO SEED
  seed:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: miniwiki-seed
    command: ["npm", "run", "seed"]
    depends_on:
      - mongo
      - elasticsearch
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - ES_URL=http://elasticsearch:9200
    networks:
      - miniwiki-net

volumes:
  esdata:
  mongodata:

networks:
  miniwiki-net:
